// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiESdEQIL_NNBU_fttbdRw3SCek0dJn4Q',
    appId: '1:945593851910:web:6109a6c5dd2a1c6665a387',
    messagingSenderId: '945593851910',
    projectId: 'parkingapp-b55ea',
    authDomain: 'parkingapp-b55ea.firebaseapp.com',
    storageBucket: 'parkingapp-b55ea.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiIEGnO-6EFYpYnS_YPCLph4wbXEB_BKY',
    appId: '1:945593851910:android:b0998cece7f9c4b565a387',
    messagingSenderId: '945593851910',
    projectId: 'parkingapp-b55ea',
    storageBucket: 'parkingapp-b55ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHOHgVfxqjSznc7gU3nagTVIZu0_Y40-A',
    appId: '1:945593851910:ios:dd79a2f1903e832065a387',
    messagingSenderId: '945593851910',
    projectId: 'parkingapp-b55ea',
    storageBucket: 'parkingapp-b55ea.firebasestorage.app',
    iosBundleId: 'com.example.parkapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHOHgVfxqjSznc7gU3nagTVIZu0_Y40-A',
    appId: '1:945593851910:ios:dd79a2f1903e832065a387',
    messagingSenderId: '945593851910',
    projectId: 'parkingapp-b55ea',
    storageBucket: 'parkingapp-b55ea.firebasestorage.app',
    iosBundleId: 'com.example.parkapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiESdEQIL_NNBU_fttbdRw3SCek0dJn4Q',
    appId: '1:945593851910:web:20e63dbfc4afd18765a387',
    messagingSenderId: '945593851910',
    projectId: 'parkingapp-b55ea',
    authDomain: 'parkingapp-b55ea.firebaseapp.com',
    storageBucket: 'parkingapp-b55ea.firebasestorage.app',
  );
}
