publish_to: none
name: cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:
  uuid: ^4.5.1
  shared:
    path: '../shared'
  http: ^1.3.0
  postgres: ^3.5.4
  # path: ^1.8.0


dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0

ignore: file_names